# variables used in the build
variables:
  checkout: 0.12.6
  packaging_tag: 0.12.6-3
  iteration: '3'
  pre_release: false
  draft: false

# package builds will always be manually triggered
trigger: none

jobs:
- job: 'docker'
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      archlinux_amd64:
        target: archlinux-amd64
  timeoutInMinutes: 0
  steps:
  - script: |
      echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
      sudo systemctl restart docker
      python build docker-images $(target)
    displayName: 'setup build environment'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build package-docker --clean --iteration $(iteration) $(target) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        targets/*.deb
        targets/*.rpm
        targets/*.7z
        targets/*.xz
- job: 'self_hosted'
  pool:
    name: 'docker'
  strategy:
    matrix:
      buster_raspberrypi:
        target: raspberrypi.buster-armhf
      centos8_ppc64le:
        target: centos8-ppc64le
  timeoutInMinutes: 0
  condition: eq(1, 2)
  steps:
  - script: |
      rm -fr wkhtmltopdf targets && git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build package-docker --clean --iteration $(iteration) $(target) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        targets/*.deb
        targets/*.rpm
        targets/*.7z
- job: 'msvc2015'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      win64:
        target: msvc2015-win64
      win32:
        target: msvc2015-win32
  timeoutInMinutes: 0
  condition: eq(1, 2)
  steps:
  - script: |
      choco install -yr --no-progress vcbuildtools -ia "/Full"
      pip install -q conan
      cmd /c attrib "C:\Program Files (x86)\Windows Kits\10\include\wdf" +H
    displayName: 'install dependencies'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build vagrant $(target) --version - - --iteration $(iteration) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        *.exe
- job: 'macos'
  pool:
    vmImage: 'macOS-10.15'
  strategy:
    matrix:
      cocoa:
        target: macos-cocoa
  timeoutInMinutes: 0
  condition: eq(1, 2)
  steps:
  - script: |
      brew install conan
      pip3 install pyyaml
      sudo gem install fpm
      sudo xcode-select --switch /Library/Developer/CommandLineTools
    displayName: 'install dependencies'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
      sed -i -e 's/CFLAGS CXXFLAGS LDFLAGS/CFLAGS CXXFLAGS OBJECTIVE_CFLAGS LDFLAGS/g' qt/configure
      sed -i -e 's/compiler.version=9.0/compiler.version=11.0/g' ../.conan/profiles/macos-cocoa
    displayName: 'clone wkhtmltopdf'
  - script: MACOSX_DEPLOYMENT_TARGET=10.7 python3 build vagrant $(target) --clean --version - - --iteration $(iteration) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: github_ashkulz
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        *.pkg
