docker-prefix: wkhtmltopdf/packaging:0.12-

docker-targets:
  stretch_64:
    source: provision/Dockerfile.debian
    image:  debian:stretch
    args:
      ssl:  libssl1.0-dev

  stretch_32:
    source: provision/Dockerfile.debian
    image:  i386/debian:stretch
    args:
      ssl:  libssl1.0-dev

  jessie_64:
    source: provision/Dockerfile.debian
    image:  debian:jessie

  jessie_32:
    source: provision/Dockerfile.debian
    image:  i386/debian:jessie

  xenial_64:
    source: provision/Dockerfile.debian
    image:  ubuntu:xenial
    args:
      jpeg: libjpeg-turbo8-dev

  xenial_32:
    source: provision/Dockerfile.debian
    image:  i386/ubuntu:xenial
    args:
      jpeg: libjpeg-turbo8-dev

  trusty_64:
    source: provision/Dockerfile.debian
    image:  ubuntu:trusty
    args:
      jpeg: libjpeg-turbo8-dev

  trusty_32:
    source: provision/Dockerfile.debian
    image:  i386/ubuntu:trusty
    args:
      jpeg: libjpeg-turbo8-dev

  centos7_64:
    source: provision/Dockerfile.centos64
    image:  centos:7

  centos7_32:
    source: provision/Dockerfile.centos32
    image:  i386/centos:7

  centos6_64:
    source: provision/Dockerfile.centos64
    image:  centos:6

  centos6_32:
    source: provision/Dockerfile.centos32
    image:  i386/centos:6

qt-config:
  common: >
    -opensource
    -confirm-license
    -fast
    -release
    -static
    -graphicssystem raster
    -webkit
    -exceptions
    -xmlpatterns
    -system-zlib
    -system-libpng
    -system-libjpeg
    -no-libmng
    -no-libtiff
    -no-accessibility
    -no-stl
    -no-qt3support
    -no-phonon
    -no-phonon-backend
    -no-opengl
    -no-declarative
    -no-script
    -no-scripttools
    -no-sql-ibase
    -no-sql-mysql
    -no-sql-odbc
    -no-sql-psql
    -no-sql-sqlite
    -no-sql-sqlite2
    -no-mmx
    -no-3dnow
    -no-sse
    -no-sse2
    -no-multimedia
    -nomake demos
    -nomake docs
    -nomake examples
    -nomake tools
    -nomake tests
    -nomake translations
  docker: >
    -silent
    -xrender
    -largefile
    -iconv
    -openssl-linked
    -no-javascript-jit
    -no-rpath
    -no-dbus
    -no-nis
    -no-cups
    -no-pch
    -no-gtkstyle
    -no-nas-sound
    -no-sm
    -no-xshape
    -no-xinerama
    -no-xcursor
    -no-xfixes
    -no-xrandr
    -no-mitshm
    -no-xinput
    -no-xkb
    -no-glib
    -no-gstreamer
    -no-icu
    -no-openvg
    -no-xsync
    -no-audio-backend
    -no-sse3
    -no-ssse3
    -no-sse4.1
    -no-sse4.2
    -no-avx
    -no-neon
